name: Docker Build and Push

on:
  push:
    branches: [ "master", "main" ]
    tags: [ "v*.*.*" ]

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: jasonvip888/open-prompt-studio
  BUILDKIT_PARALLEL: "4"  # 通过环境变量控制并行度

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:latest
            network=host
      - name: Cache Optimization
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/buildx
          key: ${{ runner.os }}-docker-${{ hashFiles('docker/Dockerfile') }}-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        env:
          BUILDKITD_FLAGS: --debug
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NPM_REGISTRY=http://registry.npmmirror.com
          extra: |
            --shm-size=1g
      - name: Post-cleanup
        run: |
          docker buildx rm || true
          docker system prune -af
