name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]  # 触发分支为 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./docker  # Dockerfile 所在目录
          file: ./docker/Dockerfile  # Dockerfile 路径
          push: true
          tags: |
            jasonvip888/open-prompt-studio:latest
            jasonvip888/open-prompt-studio:${{ github.sha }}  # 使用提交哈希作为标签
