name: Docker Build and Push

on:
  push:
    branches: [ "master", "main" ]
    tags: [ "v*.*.*" ]

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: jasonvip888/open-prompt-studio

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.12
          buildkitd-config: |
            [worker.oci]
              max-parallelism = 4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/buildx
          key: ${{ runner.os }}-docker-${{ hashFiles('docker/Dockerfile') }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NPM_REGISTRY=http://registry.npmmirror.com

      - name: Cleanup
        run: |
          docker buildx prune -f
          docker image prune -af
