name: Docker Build and Push

on:
  push:
    branches: [ "master", "main" ]
    tags: [ "v*.*.*" ]

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: jasonvip888/open-prompt-studio

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process ref name
        id: process_ref
        run: |
          SAFE_REF=$(echo "${{ github.ref_name}}" | tr '/' '-' | cut -c1-30 | tr '[:upper:]' '[:lower:]')
          echo "safe_ref=$SAFE_REF" >> $GITHUB_OUTPUT

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.12.4
            network=host

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.process_ref.outputs.safe_ref }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NPM_REGISTRY=http://registry.npmmirror.com
          shm-size: "512m"  # 正确的参数位置

      - name: Post-cleanup
        run: |
          docker buildx prune -f
