name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]  # 触发tag推送时构建带版本号的镜像

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openpromptstudio:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/openpromptstudio:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
